# Generated by Django 5.2.12 on 2026-04-22 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_equipo', models.CharField(max_length=50, unique=True)),
                ('nombre_equipo', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=50)),
                ('numero_serie', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(choices=[('Operativo', 'Operativo'), ('En reparación', 'En reparación'), ('Inoperativo', 'Inoperativo'), ('Dado de baja', 'Dado de baja')], default='Operativo', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_register', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('foto_estado', models.ImageField(blank=True, null=True, upload_to='equipos/estado/', verbose_name='Foto del Estado')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'ordering': ['-fecha_register'],
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo de Equipo',
                'verbose_name_plural': 'Tipos de Equipo',
                'ordering': ['nombre'],
            },
        ),
    ]
