# Generated by Django 5.2.12 on 2026-04-24 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0005_alter_area_options_alter_area_name_and_more"),
        ("inventario", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistorialEstadoEquipo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("estado_anterior", models.CharField(choices=[("Operativo", "Operativo"), ("En reparación", "En reparación"), ("Inoperativo", "Inoperativo"), ("Dado de baja", "Dado de baja")], max_length=20)),
                ("estado_nuevo", models.CharField(choices=[("Operativo", "Operativo"), ("En reparación", "En reparación"), ("Inoperativo", "Inoperativo"), ("Dado de baja", "Dado de baja")], max_length=20)),
                ("observacion", models.TextField()),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                ("equipo", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="historial_estado", to="inventario.equipo")),
                ("usuario_que_cambio", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="cambios_estado_equipo", to="tickets.customuser")),
            ],
            options={
                "verbose_name": "Historial de Estado de Equipo",
                "verbose_name_plural": "Historiales de Estado de Equipos",
                "ordering": ["-fecha_registro"],
            },
        ),
    ]
