# Generated by Django 5.2.12 on 2026-04-25 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_equipo_estado_en_revision_and_sync'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='estado',
            field=models.CharField(choices=[('Operativo', 'Operativo'), ('En revisión', 'En revisión'), ('En reparación', 'En reparación'), ('Inoperativo', 'Inoperativo'), ('Dado de baja', 'Dado de baja')], default='Operativo', max_length=20),
        ),
        migrations.AlterField(
            model_name='historialestadoequipo',
            name='estado_anterior',
            field=models.CharField(choices=[('Operativo', 'Operativo'), ('En revisión', 'En revisión'), ('En reparación', 'En reparación'), ('Inoperativo', 'Inoperativo'), ('Dado de baja', 'Dado de baja')], max_length=20),
        ),
        migrations.AlterField(
            model_name='historialestadoequipo',
            name='estado_nuevo',
            field=models.CharField(choices=[('Operativo', 'Operativo'), ('En revisión', 'En revisión'), ('En reparación', 'En reparación'), ('Inoperativo', 'Inoperativo'), ('Dado de baja', 'Dado de baja')], max_length=20),
        ),
    ]
