# Generated by Django 5.2.12 on 2026-04-28 15:38

import inventario.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_alter_equipo_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='ficha_tecnica',
            field=models.FileField(blank=True, null=True, upload_to=inventario.models.upload_to_fichas, verbose_name='Ficha Técnica (PDF)'),
        ),
    ]
