# Generated by Django 5.2.12 on 2026-04-28 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_equipo_ficha_tecnica'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Estado de Equipo',
                'verbose_name_plural': 'Estados de Equipos',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterField(
            model_name='equipo',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.estadoequipo', verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='historialestadoequipo',
            name='estado_anterior',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='anteriores', to='inventario.estadoequipo'),
        ),
        migrations.AlterField(
            model_name='historialestadoequipo',
            name='estado_nuevo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nuevos', to='inventario.estadoequipo'),
        ),
    ]
