# Generated by Django 5.2.12 on 2026-05-06 15:23

import django.db.models.deletion
from django.db import migrations, models


def sincronizar_estado_tecnico(apps, schema_editor):
    Equipo = apps.get_model('inventario', 'Equipo')
    Equipo.objects.filter(estado_tecnico__isnull=True).update(estado_tecnico=models.F('estado'))
    Equipo.objects.filter(disponibilidad='EN_USO', origen_ocupacion__isnull=True).update(origen_ocupacion='ASIGNACION_DIRECTA')
    Equipo.objects.filter(disponibilidad='REEMPLAZO_TEMPORAL', origen_ocupacion__isnull=True).update(origen_ocupacion='REEMPLAZO')


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_equipo_disponibilidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='estado_tecnico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipos_estado_tecnico', to='inventario.estadoequipo', verbose_name='Estado técnico'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='origen_ocupacion',
            field=models.CharField(blank=True, choices=[('MANUAL', 'Manual'), ('ASIGNACION_DIRECTA', 'Asignación directa'), ('INCIDENCIA', 'Incidencia'), ('REEMPLAZO', 'Reemplazo temporal'), ('MANTENIMIENTO', 'Mantenimiento')], max_length=20, null=True, verbose_name='Origen de ocupación'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='disponibilidad',
            field=models.CharField(choices=[('LIBRE', 'Libre'), ('EN_USO', 'En uso'), ('REEMPLAZO_TEMPORAL', 'Reemplazo temporal')], default='LIBRE', max_length=30, verbose_name='Disponibilidad'),
        ),
        migrations.RunPython(sincronizar_estado_tecnico, migrations.RunPython.noop),
    ]
