# Generated by Django 5.2.12 on 2026-05-06 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_equipo_estado_tecnico_equipo_origen_ocupacion_and_more'),
        ('tickets', '0013_metricadiaria_alter_incidencia_estado_sla'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='equipo',
            index=models.Index(fields=['disponibilidad'], name='idx_equipo_disponibilidad'),
        ),
        migrations.AddIndex(
            model_name='equipo',
            index=models.Index(fields=['estado_tecnico', 'disponibilidad'], name='idx_equipo_estado_disp'),
        ),
    ]
