# Generated by Django 5.2.12 on 2026-05-07 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0011_equipo_idx_equipo_disponibilidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='disponibilidad',
            field=models.CharField(choices=[('LIBRE', 'Libre'), ('EN_USO', 'En uso'), ('REEMPLAZO_TEMPORAL', 'Reemplazo temporal'), ('NO_DISPONIBLE', 'No disponible')], default='LIBRE', max_length=30, verbose_name='Disponibilidad'),
        ),
    ]
