# Generated by Django 5.2.12 on 2026-05-19 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0012_alter_equipo_disponibilidad'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Repuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('categoria', models.CharField(blank=True, max_length=80)),
                ('unidad', models.CharField(choices=[('unidad', 'Unidad'), ('paquete', 'Paquete'), ('metro', 'Metro'), ('kit', 'Kit')], default='unidad', max_length=20)),
                ('stock_actual', models.PositiveIntegerField(default=0)),
                ('stock_minimo', models.PositiveIntegerField(default=1)),
                ('ubicacion', models.CharField(blank=True, max_length=120)),
                ('observaciones', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Repuesto',
                'verbose_name_plural': 'Repuestos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='MantenimientoPreventivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_programada', models.DateField()),
                ('frecuencia_dias', models.PositiveIntegerField(default=90)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('programado', 'Programado'), ('realizado', 'Realizado'), ('vencido', 'Vencido'), ('cancelado', 'Cancelado')], default='programado', max_length=20)),
                ('resultado', models.TextField(blank=True)),
                ('fecha_realizado', models.DateField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos_preventivos', to='inventario.equipo')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mantenimientos_preventivos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mantenimiento preventivo',
                'verbose_name_plural': 'Mantenimientos preventivos',
                'ordering': ['fecha_programada', 'equipo__codigo_equipo'],
                'indexes': [models.Index(fields=['estado', 'fecha_programada'], name='idx_mant_estado_fecha')],
            },
        ),
    ]
