# Generated by Django 5.2.12 on 2026-04-22 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.CharField(choices=[('Usuarios', 'Usuarios'), ('Inventario', 'Inventario'), ('Incidencias', 'Incidencias'), ('Sistema', 'Sistema')], max_length=50)),
                ('accion', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('referencia_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Auditoría',
                'verbose_name_plural': 'Auditorías',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
