# Generated by Django 5.2.12 on 2026-05-06 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditoria',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
