# Generated by Django 5.2.12 on 2026-05-06 15:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0003_auditoria_metadata'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditoria',
            name='evento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='auditoria',
            name='hash_evento',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddConstraint(
            model_name='auditoria',
            constraint=models.UniqueConstraint(condition=models.Q(('evento__isnull', False), ('hash_evento__isnull', False)), fields=('modulo', 'referencia_id', 'evento', 'hash_evento'), name='uniq_auditoria_evento_hash'),
        ),
    ]
