# Generated by Django 5.2.12 on 2026-05-06 16:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0004_auditoria_evento_auditoria_hash_evento_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='auditoria',
            name='uniq_auditoria_evento_hash',
        ),
        migrations.AddConstraint(
            model_name='auditoria',
            constraint=models.UniqueConstraint(fields=('evento', 'hash_evento'), name='uq_auditoria_evento_hash'),
        ),
    ]
