# Generated by Django 5.2.12 on 2026-05-06 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0005_remove_auditoria_uniq_auditoria_evento_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditoria',
            name='version_evento',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='EventoFallido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.CharField(max_length=100)),
                ('version_evento', models.PositiveIntegerField(default=1)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('procesado', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Evento fallido',
                'verbose_name_plural': 'Eventos fallidos',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['evento', 'procesado'], name='auditoria_e_evento_d26f5a_idx'), models.Index(fields=['fecha'], name='auditoria_e_fecha_0ebc43_idx')],
            },
        ),
    ]
