# Generated by Django 5.2.12 on 2026-05-06 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0006_auditoria_version_evento_eventofallido'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventofallido',
            name='intentos',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='eventofallido',
            name='ultimo_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddIndex(
            model_name='eventofallido',
            index=models.Index(fields=['procesado', 'intentos'], name='auditoria_e_procesa_a6637f_idx'),
        ),
    ]
