services:
  sgi-db:
    image: postgres:17-alpine
    container_name: sgi-db
    restart: unless-stopped
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    ports:
      - "54335:5432"
    environment:
      POSTGRES_DB: gestion_incidencias_prod
      POSTGRES_USER: gestion_prod_user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    secrets:
      - postgres_password
    networks:
      - sgi-network

  sgi-redis:
    image: redis:7-alpine
    container_name: sgi-redis
    restart: unless-stopped
    ports:
      - "6381:6379"
    volumes:
      - ./redis_data:/data
    networks:
      - sgi-network

  sgi-web:
    image: saithg04/sgi-ugel-django:latest
    container_name: sgi-web
    restart: unless-stopped
    command: /app/run_web.sh
    env_file:
      - /home/isai.quiroga.2004/environments/sgi-ugel-django.env
    volumes:
      - ./storage/static:/app/staticfiles
      - ./storage/media:/app/media
    depends_on:
      - sgi-db
      - sgi-redis
    networks:
      - sgi-network

  sgi-scheduler:
    image: saithg04/sgi-ugel-django:latest
    container_name: sgi-scheduler
    restart: unless-stopped
    command: /app/run_scheduler.sh
    env_file:
      - /home/isai.quiroga.2004/environments/sgi-ugel-django.env
    volumes:
      - ./storage/static:/app/staticfiles
      - ./storage/media:/app/media
    depends_on:
      - sgi-db
      - sgi-redis
    networks:
      - sgi-network

  cloudflared-tunnel-sgi:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared-tunnel-sgi
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token-file /run/secrets/cloudflared_token_sgi
    secrets:
      - cloudflared_token_sgi
    networks:
      - sgi-network

networks:
  sgi-network:
    name: sgi-network

secrets:
  postgres_password:
    file: ./secrets/postgres_password.txt
  cloudflared_token_sgi:
    file: ./secrets/cloudflared_token_sgi.txt



