services:
  web:
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000 --noreload"
    environment:
      DJANGO_DEBUG: "True"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media

  scheduler:
    environment:
      DJANGO_DEBUG: "True"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
