# Generated by Django 5.2.12 on 2026-04-22 16:14

import django.contrib.auth.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import tickets.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('first_name', models.CharField(max_length=150, validators=[django.core.validators.RegexValidator(message='Solo se permiten letras, espacios, tildes y la letra "ñ".', regex='^[A-Za-zÁÉÍÓÚáéíóúÑñ\\s]+$')], verbose_name='First name')),
                ('last_name', models.CharField(max_length=150, validators=[django.core.validators.RegexValidator(message='Solo se permiten letras, espacios, tildes y la letra "ñ".', regex='^[A-Za-zÁÉÍÓÚáéíóúÑñ\\s]+$')], verbose_name='Last name')),
                ('username', models.CharField(help_text='8 dígitos del DNI.', max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='El DNI debe contener exactamente 8 dígitos numéricos.', regex='^\\d{8}$')], verbose_name='DNI / Username')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('role', models.CharField(choices=[('usuario', 'Usuario (Trabajador)'), ('tecnico', 'Técnico'), ('administrador', 'Administrador/Ingeniero TI')], default='usuario', max_length=15)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='El teléfono solo permite números y un "+" inicial opcional.', regex='^\\+?\\d{7,15}$')])),
                ('foto', models.ImageField(blank=True, null=True, upload_to='perfiles/')),
                ('last_password_change', models.DateTimeField(default=django.utils.timezone.now)),
                ('must_change_password', models.BooleanField(default=False)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.area')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('hardware', 'Hardware'), ('software', 'Software'), ('red', 'Red'), ('sistema', 'Sistema')], max_length=20)),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('critica', 'Crítica')], max_length=20)),
                ('descripcion', models.TextField()),
                ('imagen_adjunta', models.ImageField(blank=True, null=True, upload_to='incidencias_imagenes/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_programada_atencion', models.DateField(blank=True, null=True)),
                ('hora_programada_atencion', models.TimeField(blank=True, null=True)),
                ('observaciones_internas', models.TextField(blank=True, null=True)),
                ('solucion_aplicada', models.TextField(blank=True, null=True)),
                ('evidencia_solucion', models.ImageField(blank=True, null=True, upload_to='soluciones_evidencias/')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.area')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidencias_creadas', to=settings.AUTH_USER_MODEL)),
                ('estado', models.ForeignKey(default=tickets.models.get_default_estado, on_delete=django.db.models.deletion.PROTECT, to='tickets.estado')),
                ('tecnico_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidencias_asignadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_comentario', models.CharField(choices=[('tecnico', 'Comentario Técnico'), ('confirmacion', 'Confirmación de Solución'), ('persiste', 'Problema Persiste'), ('observacion', 'Observación Interna')], default='observacion', max_length=20)),
                ('texto', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('evidencia_adjunta', models.ImageField(blank=True, null=True, upload_to='comentarios_evidencias/')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('incidencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='tickets.incidencia')),
            ],
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField()),
                ('tipo', models.CharField(choices=[('asignacion', 'Asignación'), ('estado', 'Cambio de Estado'), ('comentario', 'Nuevo Comentario'), ('nueva_incidencia', 'Nueva Incidencia'), ('incidencia_resuelta', 'Incidencia Resuelta'), ('desasignacion', 'Desasignación')], max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('link', models.URLField(blank=True, max_length=500, null=True)),
                ('incidencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.incidencia')),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='NotificacionUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leido', models.BooleanField(default=False)),
                ('fecha_recibida', models.DateTimeField(auto_now_add=True)),
                ('notificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='tickets.notificacion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_recibida'],
                'unique_together': {('usuario', 'notificacion')},
            },
        ),
    ]
