# Generated by Django 5.2.12 on 2026-04-23 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_initial'),
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidencia',
            name='equipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.equipo'),
        ),
        migrations.AddField(
            model_name='incidencia',
            name='otro_marca',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='incidencia',
            name='otro_modelo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='incidencia',
            name='otro_serie',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='incidencia',
            name='otro_tipo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='incidencia',
            name='categoria',
            field=models.CharField(choices=[('hardware', 'Hardware'), ('software', 'Software'), ('red', 'Red'), ('sistema', 'Sistema'), ('otros', 'Otros')], max_length=20),
        ),
    ]
