# Generated by Django 5.2.12 on 2026-04-23 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_incidencia_equipo_incidencia_otro_marca_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='sede_principal',
            field=models.CharField(blank=True, choices=[('DIRECCIÓN', 'Dirección'), ('AGP', 'AGP'), ('ADMINISTRACIÓN', 'Administración'), ('UPDI', 'UPDI')], max_length=20, null=True),
        ),
    ]
