# Generated by Django 5.2.12 on 2026-04-23 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_area_sede_principal'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidencia',
            name='fecha_cierre',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='IncidenciaImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='incidencias_adicionales/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('incidencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='tickets.incidencia')),
            ],
        ),
    ]
