# Generated by Django 5.2.12 on 2026-04-25 05:03

import django.core.validators
import tickets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_incidencia_codigo_fecha_asignacion_and_user_cleanups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='evidencia_adjunta',
            field=models.ImageField(blank=True, null=True, upload_to=tickets.models.upload_to_comentarios),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, validators=[django.core.validators.EmailValidator(message='Ingrese un correo válido con el formato ejemplo@dominio.com.')]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=tickets.models.upload_to_perfiles),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='El teléfono solo permite números.', regex='^\\d{7,15}$')]),
        ),
        migrations.AlterField(
            model_name='incidencia',
            name='evidencia_solucion',
            field=models.ImageField(blank=True, null=True, upload_to=tickets.models.upload_to_soluciones),
        ),
        migrations.AlterField(
            model_name='incidencia',
            name='imagen_adjunta',
            field=models.ImageField(blank=True, null=True, upload_to=tickets.models.upload_to_incidencias),
        ),
        migrations.AlterField(
            model_name='incidenciaimagen',
            name='imagen',
            field=models.ImageField(upload_to=tickets.models.upload_to_adicionales),
        ),
    ]
