# Generated by Django 5.2.12 on 2026-04-25 13:23

import tickets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_alter_comentario_evidencia_adjunta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidencia',
            name='evidencia_solucion_2',
            field=models.ImageField(blank=True, null=True, upload_to=tickets.models.upload_to_soluciones),
        ),
        migrations.AddField(
            model_name='incidencia',
            name='evidencia_solucion_3',
            field=models.ImageField(blank=True, null=True, upload_to=tickets.models.upload_to_soluciones),
        ),
    ]
