# Generated by Django 5.2.12 on 2026-04-26 17:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_incidencia_evidencia_solucion_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='telefono',
            field=models.CharField(default='000000000', max_length=9, validators=[django.core.validators.RegexValidator(message='El teléfono debe contener exactamente 9 dígitos.', regex='^\\d{9}$')]),
            preserve_default=False,
        ),
    ]
