# Generated by Django 5.2.12 on 2026-04-28 15:38

import tickets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_alter_customuser_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidencia',
            name='documento_informe',
            field=models.FileField(blank=True, null=True, upload_to=tickets.models.upload_to_informes),
        ),
        migrations.AddField(
            model_name='incidencia',
            name='fecha_resolucion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
