# Generated by Django 5.2.12 on 2026-05-06 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_equipo_estado_tecnico_equipo_origen_ocupacion_and_more'),
        ('tickets', '0011_incidencia_tipo_resolucion_equipo_reemplazo'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='capacidad_base',
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AddField(
            model_name='incidencia',
            name='auto_cerrado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='incidencia',
            name='escalado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='incidencia',
            name='estado_sla',
            field=models.CharField(choices=[('en_tiempo', 'En tiempo'), ('respuesta_vencida', 'Respuesta vencida'), ('resolucion_vencida', 'Resolución vencida'), ('escalado', 'Escalado'), ('cumplido', 'Cumplido'), ('no_aplica', 'No aplica')], default='en_tiempo', max_length=30),
        ),
        migrations.AddField(
            model_name='incidencia',
            name='fecha_auto_cierre',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incidencia',
            name='fecha_limite_resolucion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incidencia',
            name='fecha_limite_respuesta',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incidencia',
            name='sla_resolucion_notificado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='incidencia',
            name='sla_respuesta_notificado',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='SLAConfiguracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('critica', 'Crítica')], max_length=20)),
                ('categoria', models.CharField(blank=True, choices=[('hardware', 'Hardware'), ('software', 'Software'), ('red', 'Red'), ('sistema', 'Sistema'), ('otros', 'Otros')], max_length=20, null=True)),
                ('tiempo_respuesta_minutos', models.PositiveIntegerField(default=240)),
                ('tiempo_resolucion_minutos', models.PositiveIntegerField(default=1440)),
                ('auto_cierre_horas', models.PositiveIntegerField(default=72)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Configuración SLA',
                'verbose_name_plural': 'Configuraciones SLA',
                'unique_together': {('prioridad', 'categoria')},
            },
        ),
        migrations.CreateModel(
            name='ReemplazoEquipoIncidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField()),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('area_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tickets.area')),
                ('area_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tickets.area')),
                ('equipo_original', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reemplazos_como_original', to='inventario.equipo')),
                ('equipo_reemplazo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reemplazos_como_temporal', to='inventario.equipo')),
                ('incidencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reemplazos', to='tickets.incidencia')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reemplazos_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reemplazo de equipo por incidencia',
                'verbose_name_plural': 'Reemplazos de equipos por incidencias',
                'indexes': [models.Index(fields=['incidencia', 'activo'], name='tickets_ree_inciden_d58e95_idx'), models.Index(fields=['equipo_reemplazo', 'activo'], name='tickets_ree_equipo__cd94e0_idx')],
            },
        ),
        migrations.RunPython(
            lambda apps, schema_editor: [
                apps.get_model('tickets', 'Estado').objects.get_or_create(name=nombre)
                for nombre in [
                    'Pendiente',
                    'Asignado',
                    'En Proceso',
                    'Rechazado',
                    'Reabierto',
                    'Pendiente de validación',
                    'Resuelto',
                    'Cerrado',
                ]
            ],
            migrations.RunPython.noop,
        ),
    ]
