# Generated by Django 5.2.12 on 2026-05-06 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0012_customuser_capacidad_base_incidencia_auto_cerrado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricaDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
                ('tickets_abiertos', models.PositiveIntegerField(default=0)),
                ('tickets_cerrados', models.PositiveIntegerField(default=0)),
                ('sla_vencidos', models.PositiveIntegerField(default=0)),
                ('sla_por_vencer', models.PositiveIntegerField(default=0)),
                ('tickets_validacion_vencidos', models.PositiveIntegerField(default=0)),
                ('equipos_reparacion_sin_ticket_activo', models.PositiveIntegerField(default=0)),
                ('reemplazos_activos', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Métrica diaria',
                'verbose_name_plural': 'Métricas diarias',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AlterField(
            model_name='incidencia',
            name='estado_sla',
            field=models.CharField(choices=[('en_tiempo', 'En tiempo'), ('por_vencer', 'Por vencer'), ('respuesta_vencida', 'Respuesta vencida'), ('resolucion_vencida', 'Resolución vencida'), ('escalado', 'Escalado'), ('cumplido', 'Cumplido'), ('no_aplica', 'No aplica')], default='en_tiempo', max_length=30),
        ),
    ]
