# Generated by Django 5.2.12 on 2026-05-06 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0011_equipo_idx_equipo_disponibilidad_and_more'),
        ('tickets', '0013_metricadiaria_alter_incidencia_estado_sla'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='incidencia',
            index=models.Index(fields=['estado', 'prioridad'], name='idx_inc_estado_prioridad'),
        ),
        migrations.AddIndex(
            model_name='incidencia',
            index=models.Index(fields=['prioridad'], name='idx_inc_prioridad'),
        ),
        migrations.AddIndex(
            model_name='incidencia',
            index=models.Index(fields=['fecha_limite_resolucion'], name='idx_inc_limite_resol'),
        ),
        migrations.AddIndex(
            model_name='incidencia',
            index=models.Index(fields=['fecha_limite_respuesta'], name='idx_inc_limite_resp'),
        ),
        migrations.AddIndex(
            model_name='incidencia',
            index=models.Index(fields=['estado_sla'], name='idx_inc_estado_sla'),
        ),
        migrations.AddIndex(
            model_name='reemplazoequipoincidencia',
            index=models.Index(fields=['activo'], name='idx_reemplazo_activo'),
        ),
    ]
