# Generated by Django 5.2.12 on 2026-05-06 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0011_equipo_idx_equipo_disponibilidad_and_more'),
        ('tickets', '0014_incidencia_idx_inc_estado_prioridad_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='incidencia',
            index=models.Index(fields=['estado', 'fecha_limite_resolucion'], name='idx_inc_estado_lim_res'),
        ),
    ]
