# Generated by Django 5.2.12 on 2026-05-06 17:21

import tickets.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0015_incidencia_idx_inc_estado_lim_res'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', tickets.models.CustomUserManager()),
            ],
        ),
    ]
