# Generated by Codex on 2026-05-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0016_alter_customuser_managers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("usuario", "Usuario (Trabajador)"),
                    ("tecnico", "Técnico"),
                    ("administrador", "Administrador/Ingeniero TI"),
                    ("almacen", "Responsable de Almacén"),
                ],
                default="usuario",
                max_length=15,
            ),
        ),
    ]
