# Generated by Django 5.2.12 on 2026-05-19 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0017_alter_customuser_role_almacen'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='prioridad',
            field=models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', max_length=20),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('asignacion', 'Asignación'), ('estado', 'Cambio de Estado'), ('comentario', 'Nuevo Comentario'), ('nueva_incidencia', 'Nueva Incidencia'), ('incidencia_resuelta', 'Incidencia Resuelta'), ('desasignacion', 'Desasignación'), ('sla', 'Alerta SLA'), ('inventario', 'Inventario')], max_length=50),
        ),
    ]
